/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModelsGnssData } from '../models/models-gnss-data';
export interface ModelsGnssDataSummary {
  avgSpeed: number;
  data: Array<ModelsGnssData>;
  maxSpeed: number;
  minSpeed: number;
  trackerId: number;
}
