/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsGnssData {
  id: number;
  latitude: number;
  longitude: number;
  speed?: number;
  timestamp: string;
  trackerId: number;
}
